version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: gamdom_admin
      DB_PASSWORD: admin_gamdom
      DB_NAME: gamdom_sports_bet_db

  db:
    image: postgres:15
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: gamdom_admin
      POSTGRES_PASSWORD: admin_gamdom
      POSTGRES_DB: gamdom_sports_bet_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
